name: Post-merge cleanup
run-name: cleaned up working branches
on:
    push:
        branches:
            - main
jobs:
    post_merge_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repo
              uses: actions/checkout@4
              with:
                fetch-depth: 1
            
            - name: Get merged branch name
              run: |
                MERGED_BRANCH=$(git log --merges --oneline --first-parent -n 1 | awk '{print $NF}')
                echo "Merged branch: $MERGED_BRANCH"
                echo "MERGED_BRANCH=$MERGED_BRANCH" >> $GITHUB_ENV
            
            - name: Delete old branch
              run: |
                git branch -D ${{ env.MERGED_BRANCH }}